// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYoBe0SxBkbsPknPpA3uw4OvKiKS5cKwQ',
    appId: '1:532899171937:web:57af5ad9466736220e2420',
    messagingSenderId: '532899171937',
    projectId: 'klayons123',
    authDomain: 'klayons123.firebaseapp.com',
    storageBucket: 'klayons123.firebasestorage.app',
    measurementId: 'G-VK0JM2X9XL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLTs-FcfSoKZ2qNBjDo1Z-PoUZ3LiYSdo',
    appId: '1:532899171937:android:30aac97daeb19ae20e2420',
    messagingSenderId: '532899171937',
    projectId: 'klayons123',
    storageBucket: 'klayons123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwMeJhkBLaOqUfJYBX6ReGvaRaIYbSpFA',
    appId: '1:532899171937:ios:752dc8e7b61f584c0e2420',
    messagingSenderId: '532899171937',
    projectId: 'klayons123',
    storageBucket: 'klayons123.firebasestorage.app',
    iosBundleId: 'com.klayons.klayons',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwMeJhkBLaOqUfJYBX6ReGvaRaIYbSpFA',
    appId: '1:532899171937:ios:752dc8e7b61f584c0e2420',
    messagingSenderId: '532899171937',
    projectId: 'klayons123',
    storageBucket: 'klayons123.firebasestorage.app',
    iosBundleId: 'com.klayons.klayons',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYoBe0SxBkbsPknPpA3uw4OvKiKS5cKwQ',
    appId: '1:532899171937:web:9774f268ef33875d0e2420',
    messagingSenderId: '532899171937',
    projectId: 'klayons123',
    authDomain: 'klayons123.firebaseapp.com',
    storageBucket: 'klayons123.firebasestorage.app',
    measurementId: 'G-MJN2YYFNE1',
  );
}
